version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
  # db:
  #   image: mysql:8.0
  #   environment:
  #     MYSQL_ROOT_PASSWORD: your_mysql_root_password
  #     MYSQL_DATABASE: your_mysql_database
  #   ports:
  #     - "3306:3306"
